import { Test, TestingModule } from '@nestjs/testing';
import { Reflector } from '@nestjs/core';
import { BadRequestException, ValidationPipe } from '@nestjs/common';
import { InventoryController } from './inventory.controller';
import { InventoryService } from '../services/inventory.service';
import { QueryInventoryItemDto, QueryInventoryLotDto, QueryInventoryStockDto, QueryPurchaseOrderDto } from '../dto/inventory.dto';
import { PERMISSIONS_KEY, RequiredPermission } from '../../shared/auth/permissions.guard';

describe('InventoryController', () => {
  let controller: InventoryController; let service: Record<string, jest.Mock>; const reflector = new Reflector();
  const permissionsFor = (handler: string): RequiredPermission[] | undefined => reflector.get<RequiredPermission[]>(PERMISSIONS_KEY, controller[handler as keyof InventoryController] as Function);
  beforeEach(async () => { service = { listSuppliers: jest.fn(), createSupplier: jest.fn(), listItems: jest.fn(), createItem: jest.fn(), getItem: jest.fn(), updateItem: jest.fn(), listLots: jest.fn(), listPurchaseOrders: jest.fn(), getPurchaseOrder: jest.fn(), createPurchaseOrder: jest.fn(), receivePurchaseOrder: jest.fn(), stock: jest.fn(), consumeStock: jest.fn() }; const module: TestingModule = await Test.createTestingModule({ controllers: [InventoryController], providers: [{ provide: InventoryService, useValue: service }] }).compile(); controller = module.get(InventoryController); });
  it('delegates all thirteen routes', async () => {
    const supplier = {}; const item = {}; const po = {}; const receipt = {}; const consumed = {}; const lots = { data: [], total: 0, page: 1, limit: 20 }; const poDetail = { order: po, items: [] };
    service.listSuppliers.mockResolvedValue([supplier]); service.createSupplier.mockResolvedValue(supplier); service.listItems.mockResolvedValue([item]); service.createItem.mockResolvedValue(item); service.getItem.mockResolvedValue(item); service.updateItem.mockResolvedValue(item); service.listLots.mockResolvedValue(lots); service.listPurchaseOrders.mockResolvedValue([po]); service.getPurchaseOrder.mockResolvedValue(poDetail); service.createPurchaseOrder.mockResolvedValue(po); service.receivePurchaseOrder.mockResolvedValue(receipt); service.stock.mockResolvedValue([]); service.consumeStock.mockResolvedValue(consumed);
    await expect(controller.listSuppliers()).resolves.toEqual([supplier]); await expect(controller.createSupplier({ name: 'S' } as never)).resolves.toBe(supplier); await expect(controller.listItems({ branch_id: 'branch-a' })).resolves.toEqual([item]); await expect(controller.createItem({} as never)).resolves.toBe(item); await expect(controller.getItem('item-1')).resolves.toBe(item); await expect(controller.updateItem('item-1', {} as never)).resolves.toBe(item); await expect(controller.listLots({ branch_id: 'branch-a' })).resolves.toEqual(lots); await expect(controller.listPurchaseOrders({ branch_id: 'branch-a' })).resolves.toEqual([po]); await expect(controller.getPurchaseOrder('po-1')).resolves.toBe(poDetail); await expect(controller.createPurchaseOrder({} as never)).resolves.toBe(po); await expect(controller.receive('po-1', receipt as never)).resolves.toBe(receipt); await expect(controller.stock({ branch_id: 'branch-a' })).resolves.toEqual([]); await expect(controller.consume(consumed as never)).resolves.toBe(consumed);
    expect(service.listItems).toHaveBeenCalledWith('branch-a'); expect(service.listPurchaseOrders).toHaveBeenCalledWith('branch-a'); expect(service.getItem).toHaveBeenCalledWith('item-1'); expect(service.updateItem).toHaveBeenCalledWith('item-1', {}); expect(service.listLots).toHaveBeenCalledWith({ branch_id: 'branch-a' }); expect(service.getPurchaseOrder).toHaveBeenCalledWith('po-1'); expect(service.receivePurchaseOrder).toHaveBeenCalledWith('po-1', receipt); expect(service.stock).toHaveBeenCalledWith('branch-a'); expect(service.consumeStock).toHaveBeenCalledWith(consumed);
  });
  it('guards all thirteen routes with the intended permissions', () => {
    expect(permissionsFor('listSuppliers')).toEqual([{ resource: 'inventory', action: 'read' }]); expect(permissionsFor('createSupplier')).toEqual([{ resource: 'inventory', action: 'create' }]); expect(permissionsFor('listItems')).toEqual([{ resource: 'inventory', action: 'read' }]); expect(permissionsFor('createItem')).toEqual([{ resource: 'inventory', action: 'create' }]); expect(permissionsFor('getItem')).toEqual([{ resource: 'inventory', action: 'read' }]); expect(permissionsFor('updateItem')).toEqual([{ resource: 'inventory', action: 'update' }]); expect(permissionsFor('listLots')).toEqual([{ resource: 'inventory', action: 'read' }]); expect(permissionsFor('listPurchaseOrders')).toEqual([{ resource: 'inventory', action: 'read' }]); expect(permissionsFor('getPurchaseOrder')).toEqual([{ resource: 'inventory', action: 'read' }]); expect(permissionsFor('createPurchaseOrder')).toEqual([{ resource: 'inventory', action: 'create' }]); expect(permissionsFor('receive')).toEqual([{ resource: 'inventory', action: 'receive' }]); expect(permissionsFor('stock')).toEqual([{ resource: 'inventory', action: 'read' }]); expect(permissionsFor('consume')).toEqual([{ resource: 'inventory', action: 'update' }]);
  });
  it('rejects a list query with a missing or malformed branch_id with a 400', async () => {
    // Same pipe config as `src/main.ts` (`whitelist: true`, `transform: true`).
    const pipe = new ValidationPipe({ whitelist: true, transform: true });
    for (const metatype of [QueryInventoryItemDto, QueryInventoryStockDto, QueryInventoryLotDto, QueryPurchaseOrderDto]) {
      await expect(pipe.transform({}, { type: 'query', metatype })).rejects.toBeInstanceOf(BadRequestException);
      await expect(pipe.transform({ branch_id: 'not-a-uuid' }, { type: 'query', metatype })).rejects.toBeInstanceOf(BadRequestException);
      await expect(pipe.transform({ branch_id: '11111111-1111-4111-8111-111111111111' }, { type: 'query', metatype })).resolves.toEqual(expect.objectContaining({ branch_id: '11111111-1111-4111-8111-111111111111' }));
    }
  });
});