import { MigrationInterface, QueryRunner } from 'typeorm';
export class CreateCrmLeadManagement1788965263266 implements MigrationInterface {
  name = 'CreateCrmLeadManagement1788965263266';
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE "CRM_LEAD_SOURCES" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" varchar(100) NOT NULL, "description" text, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_crm_sources" PRIMARY KEY ("id"))`);
    await q.query(`CREATE TABLE "CRM_LEAD_STAGES" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" varchar(100) NOT NULL, "key" varchar(50) NOT NULL, "description" text, "sort_order" int NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_crm_stages" PRIMARY KEY ("id"))`);
    await q.query(`CREATE TABLE "CRM_LEADS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "source_id" uuid, "stage_id" uuid, "first_name" varchar(255) NOT NULL, "last_name" varchar(255) NOT NULL, "phone" varchar(255), "email" varchar(255), "status" varchar(50) NOT NULL DEFAULT 'new', "member_id" uuid, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_crm_leads" PRIMARY KEY ("id"))`);
    await q.query(`CREATE TABLE "CRM_LEAD_ACTIVITIES" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "lead_id" uuid NOT NULL, "activity_type" varchar(50) NOT NULL, "occurred_at" timestamptz NOT NULL DEFAULT now(), "notes" text, "created_by" uuid, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_crm_activities" PRIMARY KEY ("id"))`);
    await q.query(`CREATE TABLE "CRM_CONVERSIONS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "lead_id" uuid NOT NULL, "member_id" uuid NOT NULL, "membership_id" uuid, "conversion_date" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_crm_conversions" PRIMARY KEY ("id"))`);
    for (const sql of [`CREATE INDEX "IDX_crm_leads_org_branch_status" ON "CRM_LEADS" ("organization_id","branch_id","status")`,`CREATE INDEX "IDX_crm_sources_org" ON "CRM_LEAD_SOURCES" ("organization_id")`,`CREATE UNIQUE INDEX "UQ_crm_sources_org_name" ON "CRM_LEAD_SOURCES" ("organization_id","name")`,`CREATE INDEX "IDX_crm_stages_org_sort" ON "CRM_LEAD_STAGES" ("organization_id","sort_order")`,`CREATE INDEX "IDX_crm_activities_org_lead" ON "CRM_LEAD_ACTIVITIES" ("organization_id","lead_id","occurred_at")`,`CREATE UNIQUE INDEX "UQ_crm_conversions_org_lead" ON "CRM_CONVERSIONS" ("organization_id","lead_id")`]) await q.query(sql);
    for (const [table, col, ref] of [['CRM_LEADS','organization_id','TENANCY_ORGANIZATIONS(id)'],['CRM_LEADS','branch_id','TENANCY_BRANCHES(id)'],['CRM_LEAD_ACTIVITIES','organization_id','TENANCY_ORGANIZATIONS(id)'],['CRM_LEAD_ACTIVITIES','lead_id','CRM_LEADS(id)'],['CRM_CONVERSIONS','organization_id','TENANCY_ORGANIZATIONS(id)'],['CRM_CONVERSIONS','lead_id','CRM_LEADS(id)'],['CRM_LEAD_SOURCES','organization_id','TENANCY_ORGANIZATIONS(id)'],['CRM_LEAD_STAGES','organization_id','TENANCY_ORGANIZATIONS(id)']]) await q.query(`ALTER TABLE "${table}" ADD CONSTRAINT "FK_${table}_${col}" FOREIGN KEY ("${col}") REFERENCES "${ref.split('(')[0]}"("${ref.split('(')[1].replace(')','')}")`);
    await q.query(`ALTER TABLE "CRM_LEADS" ADD CONSTRAINT "FK_crm_leads_source" FOREIGN KEY ("source_id") REFERENCES "CRM_LEAD_SOURCES"("id")`); await q.query(`ALTER TABLE "CRM_LEADS" ADD CONSTRAINT "FK_crm_leads_stage" FOREIGN KEY ("stage_id") REFERENCES "CRM_LEAD_STAGES"("id")`);
  }
  async down(q: QueryRunner): Promise<void> { await q.query(`DROP TABLE IF EXISTS "CRM_CONVERSIONS"`); await q.query(`DROP TABLE IF EXISTS "CRM_LEAD_ACTIVITIES"`); await q.query(`DROP TABLE IF EXISTS "CRM_LEADS"`); await q.query(`DROP TABLE IF EXISTS "CRM_LEAD_STAGES"`); await q.query(`DROP TABLE IF EXISTS "CRM_LEAD_SOURCES"`); }
}