import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Phase 2B — Provision the operator AI usage-visibility RBAC baseline.
 *
 * The operator usage view (`GET /v1/organizations/:orgId/ai/usage`) is guarded
 * by `@RequirePermissions({ resource: 'ai', action: 'usage-read' })`. Exactly
 * like the two analysis permissions before it, the permission must exist in the
 * migration-controlled baseline: a database provisioned from migrations only
 * would otherwise hold no such permission (and no role association), so the
 * endpoint would return 403 for every user.
 *
 * This migration creates the permission, ensures the shared `owner` role exists
 * and links the two — the same role used by the existing development bootstrap
 * and RBAC model. It reuses the existing authorization system; it does not
 * introduce a second one.
 *
 * Design notes (derived from the CURRENT schema, not assumptions):
 *   - `IDENTITY_PERMISSIONS`, `IDENTITY_ROLES` and `IDENTITY_ROLE_PERMISSIONS`
 *     have NO unique constraints other than their primary keys, so idempotency
 *     is implemented with explicit SELECT-then-INSERT lookups keyed on the
 *     stable business columns (`resource`+`action`, `name`, `role_id`+`permission_id`).
 *   - No development UUID is hardcoded; ids are generated by the database.
 *   - The role column is `name` (there is no `code` column).
 *   - This migration touches ONLY its own permission triple; the retention and
 *     plan-performance permissions are left untouched.
 */
export const AI_USAGE_PERMISSION = {
  name: 'ai:usage-read',
  description: 'View organization AI usage and cost',
  resource: 'ai',
  action: 'usage-read',
} as const;

/** Role intended to hold AI usage-read access (matches bootstrap-dev.ts). */
export const AI_USAGE_ROLE_NAME = 'owner';

export class ProvisionAiUsagePermission1788965263232 implements MigrationInterface {
    name = 'ProvisionAiUsagePermission1788965263232'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const permissionId = await ensureUsagePermission(queryRunner);
        const roleId = await ensureOwnerRole(queryRunner);
        await ensureRolePermission(queryRunner, roleId, permissionId);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Remove ONLY what this migration is responsible for: the association
        // between the `owner` role and the AI usage-read permission, and the
        // permission row itself. The shared `owner` role is preserved because it
        // is a general RBAC role that may already exist (and be in use)
        // independently of this migration — deleting it could destroy unrelated
        // user-role / membership grants.
        await queryRunner.query(
            `DELETE FROM "IDENTITY_ROLE_PERMISSIONS" rp
             USING "IDENTITY_ROLES" r, "IDENTITY_PERMISSIONS" p
             WHERE rp."role_id" = r."id"
               AND rp."permission_id" = p."id"
               AND r."name" = $1
               AND p."resource" = $2
               AND p."action" = $3`,
            [AI_USAGE_ROLE_NAME, AI_USAGE_PERMISSION.resource, AI_USAGE_PERMISSION.action],
        );

        await queryRunner.query(
            `DELETE FROM "IDENTITY_PERMISSIONS" WHERE "resource" = $1 AND "action" = $2`,
            [AI_USAGE_PERMISSION.resource, AI_USAGE_PERMISSION.action],
        );
    }

}


/**
 * Return the id of the existing AI usage-read permission, creating it when
 * absent. Idempotent without relying on a unique constraint.
 */
async function ensureUsagePermission(queryRunner: QueryRunner): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_PERMISSIONS"
         WHERE "resource" = $1 AND "action" = $2
         ORDER BY "created_at" ASC, "id" ASC`,
        [AI_USAGE_PERMISSION.resource, AI_USAGE_PERMISSION.action],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_PERMISSIONS" ("name", "description", "resource", "action", "is_active")
         VALUES ($1, $2, $3, $4, true)
         RETURNING "id"`,
        [
            AI_USAGE_PERMISSION.name,
            AI_USAGE_PERMISSION.description,
            AI_USAGE_PERMISSION.resource,
            AI_USAGE_PERMISSION.action,
        ],
    );
    return inserted[0].id;
}

/**
 * Return the id of the intended role, creating the shared `owner` role when the
 * database does not have it yet (production is provisioned from migrations
 * only, so no roles exist prior to the first AI permission migration).
 */
async function ensureOwnerRole(queryRunner: QueryRunner): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLES"
         WHERE "name" = $1
         ORDER BY "created_at" ASC, "id" ASC`,
        [AI_USAGE_ROLE_NAME],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLES" ("name", "description", "is_active")
         VALUES ($1, $2, true)
         RETURNING "id"`,
        [AI_USAGE_ROLE_NAME, 'Owner role'],
    );
    return inserted[0].id;
}

/**
 * Link the role to the permission unless the association already exists.
 */
async function ensureRolePermission(
    queryRunner: QueryRunner,
    roleId: string,
    permissionId: string,
): Promise<void> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLE_PERMISSIONS"
         WHERE "role_id" = $1 AND "permission_id" = $2
         ORDER BY "id" ASC
         LIMIT 1`,
        [roleId, permissionId],
    );
    if (existing.length > 0) {
        return;
    }

    await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLE_PERMISSIONS" ("role_id", "permission_id")
         VALUES ($1, $2)`,
        [roleId, permissionId],
    );
}
