import { MigrationInterface, QueryRunner } from 'typeorm';

/** P3-05 inventory schema. Transactions are the stock source of truth; lots only
 * retain FIFO cost/remaining-layer state and the read model is refreshed explicitly. */
export class CreateInventorySchema1788965263264 implements MigrationInterface {
  name = 'CreateInventorySchema1788965263264';

  public async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE "INVENTORY_SUPPLIERS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" varchar(255) NOT NULL, "contact_person" varchar(255), "phone" varchar(50), "email" varchar(255), "address" varchar(500), "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_inventory_suppliers" PRIMARY KEY ("id"), CONSTRAINT "FK_inventory_suppliers_org" FOREIGN KEY ("organization_id") REFERENCES "TENANCY_ORGANIZATIONS"("id"))`);
    await q.query(`CREATE TABLE "INVENTORY_ITEMS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "name" varchar(255) NOT NULL, "sku" varchar(100) NOT NULL, "barcode" varchar(100), "unit" varchar(50) NOT NULL DEFAULT 'unit', "selling_price" numeric(15,2), "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_inventory_items" PRIMARY KEY ("id"), CONSTRAINT "UQ_inventory_items_org_branch_sku" UNIQUE ("organization_id","branch_id","sku"), CONSTRAINT "FK_inventory_items_org" FOREIGN KEY ("organization_id") REFERENCES "TENANCY_ORGANIZATIONS"("id"), CONSTRAINT "FK_inventory_items_branch" FOREIGN KEY ("branch_id") REFERENCES "TENANCY_BRANCHES"("id"))`);
    await q.query(`CREATE TABLE "INVENTORY_LOTS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "inventory_item_id" uuid NOT NULL, "lot_number" varchar(100), "expiry_date" timestamptz, "quantity" numeric(15,4) NOT NULL, "unit_cost" numeric(15,2) NOT NULL, "received_at" timestamptz NOT NULL DEFAULT now(), "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_inventory_lots" PRIMARY KEY ("id"), CONSTRAINT "FK_inventory_lots_org" FOREIGN KEY ("organization_id") REFERENCES "TENANCY_ORGANIZATIONS"("id"), CONSTRAINT "FK_inventory_lots_item" FOREIGN KEY ("inventory_item_id") REFERENCES "INVENTORY_ITEMS"("id"))`);
    await q.query(`CREATE TABLE "INVENTORY_TRANSACTIONS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "inventory_item_id" uuid NOT NULL, "transaction_type" varchar(30) NOT NULL, "quantity" numeric(15,4) NOT NULL, "unit_cost" numeric(15,2), "reference_id" uuid, "reference_type" varchar(50), "notes" varchar(500), "transaction_date" timestamptz NOT NULL DEFAULT now(), "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_inventory_transactions" PRIMARY KEY ("id"), CONSTRAINT "FK_inventory_tx_org" FOREIGN KEY ("organization_id") REFERENCES "TENANCY_ORGANIZATIONS"("id"), CONSTRAINT "FK_inventory_tx_branch" FOREIGN KEY ("branch_id") REFERENCES "TENANCY_BRANCHES"("id"), CONSTRAINT "FK_inventory_tx_item" FOREIGN KEY ("inventory_item_id") REFERENCES "INVENTORY_ITEMS"("id"))`);
    await q.query(`CREATE TABLE "INVENTORY_PURCHASE_ORDERS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "supplier_id" uuid NOT NULL, "order_date" timestamptz NOT NULL DEFAULT now(), "expected_delivery" timestamptz, "total_amount" numeric(15,2) NOT NULL DEFAULT 0, "status" varchar(30) NOT NULL DEFAULT 'open', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_inventory_pos" PRIMARY KEY ("id"), CONSTRAINT "FK_inventory_pos_org" FOREIGN KEY ("organization_id") REFERENCES "TENANCY_ORGANIZATIONS"("id"), CONSTRAINT "FK_inventory_pos_branch" FOREIGN KEY ("branch_id") REFERENCES "TENANCY_BRANCHES"("id"), CONSTRAINT "FK_inventory_pos_supplier" FOREIGN KEY ("supplier_id") REFERENCES "INVENTORY_SUPPLIERS"("id"))`);
    await q.query(`CREATE TABLE "INVENTORY_PURCHASE_ORDER_ITEMS" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "po_id" uuid NOT NULL, "inventory_item_id" uuid NOT NULL, "quantity_ordered" numeric(15,4) NOT NULL, "quantity_received" numeric(15,4) NOT NULL DEFAULT 0, "unit_cost" numeric(15,2) NOT NULL, CONSTRAINT "PK_inventory_po_items" PRIMARY KEY ("id"), CONSTRAINT "UQ_inventory_po_item" UNIQUE ("po_id","inventory_item_id"), CONSTRAINT "FK_inventory_poi_po" FOREIGN KEY ("po_id") REFERENCES "INVENTORY_PURCHASE_ORDERS"("id") ON DELETE CASCADE, CONSTRAINT "FK_inventory_poi_item" FOREIGN KEY ("inventory_item_id") REFERENCES "INVENTORY_ITEMS"("id"))`);
    await q.query(`CREATE INDEX "IDX_inventory_tx_stock" ON "INVENTORY_TRANSACTIONS" ("organization_id","branch_id","inventory_item_id")`);
    await q.query(`CREATE INDEX "IDX_inventory_lots_fifo" ON "INVENTORY_LOTS" ("organization_id","inventory_item_id","received_at")`);
    await q.query(`CREATE MATERIALIZED VIEW "MV_INVENTORY_STOCK_LEVELS" AS SELECT t.organization_id, t.branch_id, t.inventory_item_id, COALESCE(SUM(t.quantity),0)::numeric(15,4) AS quantity_on_hand, COALESCE(SUM(t.quantity * COALESCE(t.unit_cost,0)),0)::numeric(15,2) AS transaction_value FROM "INVENTORY_TRANSACTIONS" t GROUP BY t.organization_id,t.branch_id,t.inventory_item_id`);
    await q.query(`CREATE UNIQUE INDEX "UQ_inventory_stock_levels" ON "MV_INVENTORY_STOCK_LEVELS" ("organization_id","branch_id","inventory_item_id")`);
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP MATERIALIZED VIEW IF EXISTS "MV_INVENTORY_STOCK_LEVELS"`);
    await q.query(`DROP TABLE IF EXISTS "INVENTORY_PURCHASE_ORDER_ITEMS"`);
    await q.query(`DROP TABLE IF EXISTS "INVENTORY_PURCHASE_ORDERS"`);
    await q.query(`DROP TABLE IF EXISTS "INVENTORY_TRANSACTIONS"`);
    await q.query(`DROP TABLE IF EXISTS "INVENTORY_LOTS"`);
    await q.query(`DROP TABLE IF EXISTS "INVENTORY_ITEMS"`);
    await q.query(`DROP TABLE IF EXISTS "INVENTORY_SUPPLIERS"`);
  }
}