import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Phase 6 — Provision the reports RBAC baseline.
 *
 * `src/reports/controllers/report-schemas.controller.ts` and
 * `report-jobs.controller.ts` guard their routes with
 * `@RequirePermissions({ resource: 'report', action: ... })`. Permissions are
 * rows, and a database provisioned from migrations only would hold none of them
 * (the development bootstrap script is not part of a production rollout), so
 * every report endpoint would answer 403 for every user. This migration creates
 * the four permissions piece 1's routes require and links them to the shared
 * `owner` role — the same role used by the other `Provision*Permissions`
 * migrations. It reuses the existing authorization system; it introduces no
 * second one.
 *
 * Action names come from §9.1, which declares `report:view` / `report:create` /
 * `report:edit` / `report:delete` (not the `read`/`update` spellings the older
 * resources use). §9.1 is the plan's own contract for this resource, so its
 * names are used verbatim rather than aligned to the older convention.
 *
 * Two §9.1 permissions are deliberately NOT provisioned here:
 *   - `report:export` — §8's export endpoints do not exist yet (P6-04 is blocked
 *     on P6-36's missing S3 bucket), so no route would consume the row.
 *   - `dashboard:view` — §4.4's dashboard hub is P6-08, which has no code.
 * Seeding a permission no route requires would create a grant with nothing
 * behind it; those two rows belong with the tickets that add those routes.
 *
 * Roles: §9.2 assigns report permissions to `org_admin` / `manager` / `trainer`
 * / `staff`. None of those roles exists in this codebase's RBAC — the database
 * holds exactly one role, `owner`, which every other `Provision*Permissions`
 * migration grants to. Following the surrounding convention keeps production
 * provisionable from migrations; §9.2's finer-grained matrix is a role-model
 * change, not a permission-provisioning one, and is not made here.
 *
 * Design notes (derived from the CURRENT schema):
 *   - `IDENTITY_PERMISSIONS` / `IDENTITY_ROLES` / `IDENTITY_ROLE_PERMISSIONS`
 *     have no unique constraints beyond their primary keys, so idempotency is
 *     implemented with explicit SELECT-then-INSERT lookups on the stable
 *     business columns.
 *   - No development UUID is hardcoded; ids are generated by the database.
 *   - This migration touches ONLY the report permissions.
 */
export const REPORT_PERMISSIONS = [
    {
        name: 'report:view',
        description: 'View report catalog and run reports',
        resource: 'report',
        action: 'view',
    },
    {
        name: 'report:create',
        description: 'Create custom report schemas',
        resource: 'report',
        action: 'create',
    },
    {
        name: 'report:edit',
        description: 'Edit custom report schemas',
        resource: 'report',
        action: 'edit',
    },
    {
        name: 'report:delete',
        description: 'Delete custom report schemas',
        resource: 'report',
        action: 'delete',
    },
] as const;

/** Role intended to hold report access (matches bootstrap-dev.ts and the sibling migrations). */
export const REPORT_PERMISSIONS_ROLE_NAME = 'owner';

export class ProvisionReportPermissions1788965263404 implements MigrationInterface {
    name = 'ProvisionReportPermissions1788965263404'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const roleId = await ensureOwnerRole(queryRunner);
        for (const permission of REPORT_PERMISSIONS) {
            const permissionId = await ensurePermission(queryRunner, permission);
            await ensureRolePermission(queryRunner, roleId, permissionId);
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Remove ONLY what this migration created: the role associations and the
        // permission rows. The shared `owner` role itself is preserved because it
        // may predate this migration and be in use by unrelated grants.
        for (const permission of REPORT_PERMISSIONS) {
            await queryRunner.query(
                `DELETE FROM "IDENTITY_ROLE_PERMISSIONS" rp
                 USING "IDENTITY_ROLES" r, "IDENTITY_PERMISSIONS" p
                 WHERE rp."role_id" = r."id"
                   AND rp."permission_id" = p."id"
                   AND r."name" = $1
                   AND p."resource" = $2
                   AND p."action" = $3`,
                [REPORT_PERMISSIONS_ROLE_NAME, permission.resource, permission.action],
            );

            await queryRunner.query(
                `DELETE FROM "IDENTITY_PERMISSIONS" WHERE "resource" = $1 AND "action" = $2`,
                [permission.resource, permission.action],
            );
        }
    }
}

/** Return the id of the existing permission, creating it when absent. */
async function ensurePermission(
    queryRunner: QueryRunner,
    permission: { name: string; description: string; resource: string; action: string },
): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_PERMISSIONS"
         WHERE "resource" = $1 AND "action" = $2
         ORDER BY "created_at" ASC, "id" ASC`,
        [permission.resource, permission.action],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_PERMISSIONS" ("name", "description", "resource", "action", "is_active")
         VALUES ($1, $2, $3, $4, true)
         RETURNING "id"`,
        [permission.name, permission.description, permission.resource, permission.action],
    );
    return inserted[0].id;
}

/**
 * Return the id of the intended role, creating the shared `owner` role when the
 * database does not have it yet (production is provisioned from migrations only).
 */
async function ensureOwnerRole(queryRunner: QueryRunner): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLES"
         WHERE "name" = $1
         ORDER BY "created_at" ASC, "id" ASC`,
        [REPORT_PERMISSIONS_ROLE_NAME],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLES" ("name", "description", "is_active")
         VALUES ($1, $2, true)
         RETURNING "id"`,
        [REPORT_PERMISSIONS_ROLE_NAME, 'Owner role'],
    );
    return inserted[0].id;
}

/** Link the role to the permission unless the association already exists. */
async function ensureRolePermission(
    queryRunner: QueryRunner,
    roleId: string,
    permissionId: string,
): Promise<void> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLE_PERMISSIONS"
         WHERE "role_id" = $1 AND "permission_id" = $2
         ORDER BY "id" ASC
         LIMIT 1`,
        [roleId, permissionId],
    );
    if (existing.length > 0) {
        return;
    }

    await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLE_PERMISSIONS" ("role_id", "permission_id")
         VALUES ($1, $2)`,
        [roleId, permissionId],
    );
}
