import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Phase 1 — Provision the finance RBAC baseline.
 *
 * `InvoicesController` / `PaymentsController` guard their routes with
 * `@RequirePermissions({ resource: 'finance', action: ... })`. Permissions are
 * rows, and a database provisioned from migrations only would hold none of them,
 * so every finance endpoint would answer 403 for every user. This migration
 * creates the four permissions and links them to the shared `owner` role — the
 * same role used by the existing AI permission migrations and the RBAC model. It
 * reuses the existing authorization system; it introduces no second one.
 *
 * Note the deliberate split: creating an invoice (`finance:create`), voiding one
 * (`finance:update`) and taking money (`finance:record-payment`) are separate
 * actions, so a front-desk role can be granted "record payments" without also
 * being allowed to create or void invoices.
 *
 * Design notes (derived from the CURRENT schema):
 *   - `IDENTITY_PERMISSIONS` / `IDENTITY_ROLES` / `IDENTITY_ROLE_PERMISSIONS`
 *     have no unique constraints beyond their primary keys, so idempotency is
 *     implemented with explicit SELECT-then-INSERT lookups on the stable business
 *     columns.
 *   - No development UUID is hardcoded; ids are generated by the database.
 *   - This migration touches ONLY the finance permissions.
 */
export const FINANCE_PERMISSIONS = [
  {
    name: 'finance:read',
    description: 'Read invoices and payments',
    resource: 'finance',
    action: 'read',
  },
  {
    name: 'finance:create',
    description: 'Create invoices',
    resource: 'finance',
    action: 'create',
  },
  {
    name: 'finance:update',
    description: 'Void invoices',
    resource: 'finance',
    action: 'update',
  },
  {
    name: 'finance:record-payment',
    description: 'Record payments against invoices',
    resource: 'finance',
    action: 'record-payment',
  },
] as const;

/** Role intended to hold finance access (matches bootstrap-dev.ts). */
export const FINANCE_PERMISSIONS_ROLE_NAME = 'owner';

export class ProvisionFinancePermissions1788965263236 implements MigrationInterface {
    name = 'ProvisionFinancePermissions1788965263236'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const roleId = await ensureOwnerRole(queryRunner);
        for (const permission of FINANCE_PERMISSIONS) {
            const permissionId = await ensurePermission(queryRunner, permission);
            await ensureRolePermission(queryRunner, roleId, permissionId);
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Remove ONLY what this migration created: the role associations and the
        // permission rows. The shared `owner` role itself is preserved because it
        // may predate this migration and be in use by unrelated grants.
        for (const permission of FINANCE_PERMISSIONS) {
            await queryRunner.query(
                `DELETE FROM "IDENTITY_ROLE_PERMISSIONS" rp
                 USING "IDENTITY_ROLES" r, "IDENTITY_PERMISSIONS" p
                 WHERE rp."role_id" = r."id"
                   AND rp."permission_id" = p."id"
                   AND r."name" = $1
                   AND p."resource" = $2
                   AND p."action" = $3`,
                [FINANCE_PERMISSIONS_ROLE_NAME, permission.resource, permission.action],
            );

            await queryRunner.query(
                `DELETE FROM "IDENTITY_PERMISSIONS" WHERE "resource" = $1 AND "action" = $2`,
                [permission.resource, permission.action],
            );
        }
    }
}

/** Return the id of the existing permission, creating it when absent. */
async function ensurePermission(
    queryRunner: QueryRunner,
    permission: { name: string; description: string; resource: string; action: string },
): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_PERMISSIONS"
         WHERE "resource" = $1 AND "action" = $2
         ORDER BY "created_at" ASC, "id" ASC`,
        [permission.resource, permission.action],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_PERMISSIONS" ("name", "description", "resource", "action", "is_active")
         VALUES ($1, $2, $3, $4, true)
         RETURNING "id"`,
        [permission.name, permission.description, permission.resource, permission.action],
    );
    return inserted[0].id;
}

/**
 * Return the id of the intended role, creating the shared `owner` role when the
 * database does not have it yet (production is provisioned from migrations only).
 */
async function ensureOwnerRole(queryRunner: QueryRunner): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLES"
         WHERE "name" = $1
         ORDER BY "created_at" ASC, "id" ASC`,
        [FINANCE_PERMISSIONS_ROLE_NAME],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLES" ("name", "description", "is_active")
         VALUES ($1, $2, true)
         RETURNING "id"`,
        [FINANCE_PERMISSIONS_ROLE_NAME, 'Owner role'],
    );
    return inserted[0].id;
}

/** Link the role to the permission unless the association already exists. */
async function ensureRolePermission(
    queryRunner: QueryRunner,
    roleId: string,
    permissionId: string,
): Promise<void> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLE_PERMISSIONS"
         WHERE "role_id" = $1 AND "permission_id" = $2
         ORDER BY "id" ASC
         LIMIT 1`,
        [roleId, permissionId],
    );
    if (existing.length > 0) {
        return;
    }

    await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLE_PERMISSIONS" ("role_id", "permission_id")
         VALUES ($1, $2)`,
        [roleId, permissionId],
    );
}
