import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * F2 — Provision the AI retention-analysis RBAC baseline through migrations.
 *
 * Before this migration, `ai:retention-analysis` existed ONLY in the
 * development-only `src/scripts/bootstrap-dev.ts` seed. A production database
 * created exclusively from migrations therefore contained neither the
 * permission nor its role association, so the already-implemented
 * `POST /v1/organizations/:orgId/ai/retention-analysis` endpoint (guarded by
 * `@RequirePermissions({ resource: 'ai', action: 'retention-analysis' })`)
 * returned 403 for every user.
 *
 * This migration makes the permission part of the migration-controlled
 * baseline and links it to the role that is intended to hold it — the same
 * `owner` role used by the existing development bootstrap and RBAC model.
 *
 * Design notes (derived from the CURRENT schema, not assumptions):
 *   - `IDENTITY_PERMISSIONS`, `IDENTITY_ROLES` and `IDENTITY_ROLE_PERMISSIONS`
 *     have NO unique constraints other than their primary keys, so idempotency
 *     is implemented with explicit SELECT-then-INSERT lookups keyed on the
 *     stable business columns (`resource`+`action`, `name`, `role_id`+`permission_id`).
 *   - No development UUID is hardcoded; ids are generated by the database.
 *   - The role column is `name` (there is no `code` column).
 */
export const AI_RETENTION_PERMISSION = {
  name: 'ai:retention-analysis',
  description: 'Run AI retention analysis',
  resource: 'ai',
  action: 'retention-analysis',
} as const;

/** Role intended to hold AI retention-analysis access (matches bootstrap-dev.ts). */
export const AI_RETENTION_ROLE_NAME = 'owner';

export class ProvisionAiRetentionPermission1788965263230 implements MigrationInterface {
    name = 'ProvisionAiRetentionPermission1788965263230'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const permissionId = await ensureRetentionPermission(queryRunner);
        const roleId = await ensureOwnerRole(queryRunner);
        await ensureRolePermission(queryRunner, roleId, permissionId);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Remove ONLY what this migration is responsible for: the association
        // between the `owner` role and the AI retention-analysis permission,
        // and the permission row itself. The shared `owner` role is preserved
        // because it is a general RBAC role that may already exist (and be in
        // use) independently of this migration — deleting it could destroy
        // unrelated user-role / membership grants.
        await queryRunner.query(
            `DELETE FROM "IDENTITY_ROLE_PERMISSIONS" rp
             USING "IDENTITY_ROLES" r, "IDENTITY_PERMISSIONS" p
             WHERE rp."role_id" = r."id"
               AND rp."permission_id" = p."id"
               AND r."name" = $1
               AND p."resource" = $2
               AND p."action" = $3`,
            [AI_RETENTION_ROLE_NAME, AI_RETENTION_PERMISSION.resource, AI_RETENTION_PERMISSION.action],
        );

        await queryRunner.query(
            `DELETE FROM "IDENTITY_PERMISSIONS" WHERE "resource" = $1 AND "action" = $2`,
            [AI_RETENTION_PERMISSION.resource, AI_RETENTION_PERMISSION.action],
        );
    }

}

/**
 * Return the id of the existing AI retention-analysis permission, creating it
 * when absent. Idempotent without relying on a unique constraint.
 */
async function ensureRetentionPermission(queryRunner: QueryRunner): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_PERMISSIONS"
         WHERE "resource" = $1 AND "action" = $2
         ORDER BY "created_at" ASC, "id" ASC`,
        [AI_RETENTION_PERMISSION.resource, AI_RETENTION_PERMISSION.action],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_PERMISSIONS" ("name", "description", "resource", "action", "is_active")
         VALUES ($1, $2, $3, $4, true)
         RETURNING "id"`,
        [
            AI_RETENTION_PERMISSION.name,
            AI_RETENTION_PERMISSION.description,
            AI_RETENTION_PERMISSION.resource,
            AI_RETENTION_PERMISSION.action,
        ],
    );
    return inserted[0].id;
}

/**
 * Return the id of the intended role, creating the shared `owner` role when the
 * database does not have it yet (production is provisioned from migrations
 * only, so no roles exist prior to this point).
 */
async function ensureOwnerRole(queryRunner: QueryRunner): Promise<string> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLES"
         WHERE "name" = $1
         ORDER BY "created_at" ASC, "id" ASC`,
        [AI_RETENTION_ROLE_NAME],
    );
    if (existing.length > 0) {
        return existing[0].id;
    }

    const inserted: Array<{ id: string }> = await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLES" ("name", "description", "is_active")
         VALUES ($1, $2, true)
         RETURNING "id"`,
        [AI_RETENTION_ROLE_NAME, 'Owner role'],
    );
    return inserted[0].id;
}

/**
 * Link the role to the permission unless the association already exists.
 */
async function ensureRolePermission(
    queryRunner: QueryRunner,
    roleId: string,
    permissionId: string,
): Promise<void> {
    const existing: Array<{ id: string }> = await queryRunner.query(
        `SELECT "id" FROM "IDENTITY_ROLE_PERMISSIONS"
         WHERE "role_id" = $1 AND "permission_id" = $2
         ORDER BY "id" ASC
         LIMIT 1`,
        [roleId, permissionId],
    );
    if (existing.length > 0) {
        return;
    }

    await queryRunner.query(
        `INSERT INTO "IDENTITY_ROLE_PERMISSIONS" ("role_id", "permission_id")
         VALUES ($1, $2)`,
        [roleId, permissionId],
    );
}
